# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Blocstagram' do
pod 'UICKeyChainStore'
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Blocstagram

end
